<?php defined('SYSPATH') OR die('No direct access allowed.');
/**
 * Map controller
 
 */
class Map_Controller extends Check_Controller {

    // Set the name of the template to use
    public $template = 'kohana/template_full';



    public function  __construct() {
        parent::__construct();
    }

    public function index() {

        //$map = ORM::factory('site', 1);

        // In Kohana, all views are loaded and treated as objects.
        $this->template->content = new View('admin/map_content');


        $this->template->content->content = new View('admin/rubric_content');
        $this->template->content->userinfo = new View('admin/userinfo_content');
        // You can assign anything variable to a view by using standard OOP
        // methods. In my welcome view, the $title variable will be assigned
        // the value I give it here.
        $this->template->title = 'НаКарте.kz - Карта';
        $this->rubrics = ORM::factory('rubric')->where('rubric_id', null)->find_all();

    }

    public function update() {
        $this->template->title = 'update';
        $this->template->content = null;

        if($_GET)
            {
                $id = (int)$_GET["id"];
                $lat = (float)$_GET["lat"];
                $lon = (float)$_GET["lon"];
                $city = ORM::factory("city")->find($id);
                $city->lat = $lat;
                $city->lon = $lon;
                $city->save();
                print "$id:$lat:$lon";
            }
    }

    public function __call($method, $arguments) {
        // Disable auto-rendering
        $this->auto_render = FALSE;

        // By defining a __call method, all pages routed to this controller
        // that result in 404 errors will be handled by this method, instead of
        // being displayed as "Page Not Found" errors.
        echo 'This text is generated by __call. If you expected the index page, you need to use: welcome/index/'.substr(Router::$current_uri, 8);
    }

} // End Auth_Controller