<?php defined('SYSPATH') OR die('No direct access allowed.');
/**
 * Default Kohana controller. This controller should NOT be used in production.
 * It is for demonstration purposes only!
 *
 * @package    Core
 * @author     Kohana Team
 * @copyright  (c) 2007-2008 Kohana Team
 * @license    http://kohanaphp.com/license.html
 */
class Welcome_Controller extends Template_Controller {


// Set the name of the template to use
    public $template = 'kohana/template';

    public function index() {
// In Kohana, all views are loaded and treated as objects.
        $this->template->content = new View('admin/welcome_content');

// You can assign anything variable to a view by using standard OOP
// methods. In my welcome view, the $title variable will be assigned
// the value I give it here.
        $this->template->title = 'НаКарте.kz - Добро пожаловать!';


    }

    public function logout()
    {
        $this->index();
        Auth::instance()->logout();
    }

    public function login() {
        $this->index();
        if ($_POST) {
            $post = new Validation($_POST);
            $user = $this->input->post('username');
            $pass = $this->input->post('pass');
            $this->template->title = $user . $pass;

            $user = ORM::factory('user', $user);
            $this->auth = new Auth();

            if ( ! $user->loaded) {
                $post->add_error('username', 'not_found');
            }
            elseif ($this->auth->login($user, $pass)) {
                url::redirect("/map");
            }
            else {
                $post->add_error('password', 'incorrect_password');
            }

            $this->errors = $post->errors();
        }
    }

    public function __call($method, $arguments) {
// Disable auto-rendering
        $this->auto_render = FALSE;

// By defining a __call method, all pages routed to this controller
// that result in 404 errors will be handled by this method, instead of
// being displayed as "Page Not Found" errors.
        echo 'This text is generated by __call. If you expected the index page, you need to use: welcome/index/'.substr(Router::$current_uri, 8);
    }

} // End Welcome Controller